### ISSUE TITLE
Make sure to use the correct Kibana password

### ISSUE THREAD

**Issue by widhalmt** [widhalmt/ansible-role-kibana#10]
We grep the initial passwords for the Kibana password. Newer versions create at least two Kibana passwords (more than older versions). We have to make sure to use the right one. (In version 7.10 both passwords are identical but we still need to make sure we only have one)

**Comment by martialblog** [comment]
Role will no longer be maintained. See https://github.com/NETWAYS/ansible-collection-elasticstack/
